### ISSUE TITLE
Relax state assumption?

### ISSUE THREAD

**Issue by ejschoen** [shriphani/pegasus#35]
Hi @shriphani,

Thanks for your work on pegasus!

I wonder if you would consider generalizing `pegasus.default/add-state-portions` so that it would be possible for an application to provide its own state bits that complement those added by the default state pipeline component.  If the function used `merge-with` for the `:state` entry, like this:

```clojure
(defn add-state-portions
  [config]
  (merge-with #(atom (merge @%1 @%2))
         config
         {:state (atom {})}))
```
it would be possible to populate some `:state` values in an atom outside of the call to `pegasus.core/crawl` and those initial state values wouldn't be overwritten.  The best alternative I can figure out today is to clone the default implementation of the state component.

Thanks,
Eric

**Comment by shriphani** [comment]
Sorry I took a while to respond. This looks nice. I'll add it this weekend.

**Comment by shriphani** [comment]
Hmm, so I think `pegasus.core/crawl` accepts a `config` argument that is merged with the config object. You can stick in an atom there if you want.

**Comment by ejschoen** [comment]
Well, you can stick in atom in there, but...

`(defn add-state-portions
  [config]
  (merge config
         {:state (atom {})}))`

If the config I pass in has a `{:state (atom {:key-1 ... :key-2 ...})}` then the merge in the code, as it's written today, will simply replace `:state` in the config I passed in with `(atom {})`.  The code I suggested last week would merge any values in a state map that I pass in with values that state pipeline component might want to keep (which today is empty, but in the future...).

**Comment by shriphani** [comment]
ah got it! Good catch!

**Comment by shriphani** [comment]
This look good? https://github.com/shriphani/pegasus/tree/add-custom-state-bits

**Comment by ejschoen** [comment]
yes, thanks!
