### ISSUE TITLE
Clojure 1.9 async problem

### ISSUE THREAD

**Issue by collinalexbell** [shriphani/pegasus#39]
I don't know what the update pace is for core.async, but I had problems with core.async & clojure 1.9 as documented in core.async changelog.

```
Release 0.3.442 on 2017.03.14
Fix bad :refer-clojure clause that violates new spec in Clojure 1.9.0-alpha15
```

I simply had to add this dependency to my project to fix it.

`[org.clojure/core.async "0.3.443"]`

**Comment by shriphani** [comment]
Thanks. I'll push it in a bit.
