### ISSUE TITLE
option for non-friendly crawl.

### ISSUE THREAD

**Issue by akacase** [shriphani/pegasus#41]
Is this worthwhile? It is for some things I'm trying to do in relation to security, could we possibly add this option? I'd be willing to work on a PR if this is something you'd be OK with. All that would be required is have an option to ignore `robots.txt`.

**Comment by shriphani** [comment]
sure. I don't mind at all.

**Comment by akacase** [comment]
Actually, while reading through, it seems that this option is already supported via the `:impolite?` key in the config? It seems as though this should be good to go as its included in the `default-filter` function already. Let me know if I'm correct on this and I can close this, if not, I'll proceed with the PR.

**Comment by shriphani** [comment]
Sorry I forgot about this - I believe the `:impolite?` field does what you need - let me know if you observe otherwise.

**Comment by akacase** [comment]
seems to work!
